[project]
name = "ubank"
dynamic = ["version"]
description = "Access ubank.com.au with Python"
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
authors = [{name = "eidorb"}]
dependencies = [
    "httpx>=0.28.1",
    "meatie>=0.1.28",
    "pydantic>=2.13.5",
    "soft-webauthn>=0.1.4",
    "wre-client-akamai>=3.1.1",
]

[dependency-groups]
dev = [
    "marimo>=0.17.0",
    "pytest>=8.3.4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "ubank.py"

[tool.hatch.build.targets.sdist]
only-include = [
    ".github/workflows/",
    "tests/",
    "LICENSE",
    "README.md",
    "models.py",
    "pyproject.toml",
    "soft_webauthn_patched.py",
    "ubank.py",
    "uv.lock",
]
# https://docs.astral.sh/uv/concepts/build-backend/#file-inclusion-and-exclusion
[tool.hatch.build.targets.wheel]
only-include = [
    "ubank.py",
    "models.py",
    "soft_webauthn_patched.py",
]

[project.scripts]
ubank = "ubank:cli"
